# Generated by Django 2.0 on 2019-11-26 14:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20191126_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
